export default {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    ADD_TODO: 'ADD_TODO',
    TODO_COMPLETE: 'TODO_COMPLETE',
    REMOVE_TODO: 'REMOVE_TODO',
    ADD_SUB_TODO: 'ADD_SUB_TODO',
    SUBTODO_COMPLETE: 'SUBTODO_COMPLETE',
    REMOVE_SUBTODO: 'REMOVE_SUBTODO',
};
